eclipse-tractusx/policy-hub

.tractusx
The trg https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5 asks for a product name.
This product name is used in the overview dashboard https://eclipse-tractusx.github.io/sig-release/ were the policy-hub entry is visible as empty (see the top first entry without a name but a broken heart.
=> Set product name in .tractusx

charts/policy-hub/templates/_helpers.tpl, charts/policy-hub/templates/deployment-hub.yaml, charts/policy-hub/templates/ingress.yaml, charts/policy-hub/templates/job-policy-hub-migrations.yaml, charts/policy-hub/templates/service-hub.yaml, charts/policy-hub/values.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
- use templates for unique resource names
- fix wrong service name in ingress
improve helm chart
follow up to https://github.com/eclipse-tractusx/policy-hub/pull/11
=> feat(helm-chart): use templates for unique resource names

.github/pull_request_template.md, NOTICE.md, charts/policy-hub/Chart.yaml, charts/policy-hub/templates/deployment-hub.yaml, charts/policy-hub/templates/job-policy-hub-migrations.yaml, charts/policy-hub/values.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-rc.yaml, docker/Dockerfile-policy-hub-migrations, docker/Dockerfile-policy-hub-service, docs/technical-documentation/architecture/Development Concept.md, scripts/add_notice_footer.sh, scripts/license.sh, src/.vscode/settings.json
- feat(trg-4.07): enable readOnlyRootFilesystem for containers
- feat: make imagePullPolicy configurable, default set to IfNotPresent
- chore: add registry to image
- chore: update notice
- chore: add and update file header templates
- docs: fix broken links
prepare 0.1.0 version
https://github.com/eclipse-tractusx/portal-cd/issues/159
=> feat: improve helm chart and chores for 0.1.0

.github/workflows/chart-release.yaml
push git tag after chart release for release workflow to be triggered
improve on release automation
na
=> chore: push git tag after chart release

.github/workflows/owasp-zap.yml
remove summary and set retention-days for OWASP ZAP scan
[example run](https://github.com/eclipse-tractusx/policy-hub/actions/runs/7919313113)
feedback from sec team
https://github.com/eclipse-tractusx/policy-hub/issues/29
=> chore(dast-owasp-zap): remove summary and set retention-days

.github/workflows/chart-release.yaml
fix git tag push after chart release
follow up to https://github.com/eclipse-tractusx/policy-hub/pull/34
=> chore: fix git tag push after chart release

charts/policy-hub/templates/_helpers.tpl, charts/policy-hub/templates/deployment-hub.yaml, charts/policy-hub/templates/job-policy-hub-migrations.yaml
helm-chart: define templates for db hostname uniquely
improve helm-chart for umbrella use case
=> feat(helm-chart): define templates for db hostname uniquely

.github/workflows/dependencies.yml
A new version of the dash tool has been pushed to the repository but the workflow wasn't updated.
Fix workflow
Solves #49
=> chore(ci): fix dash tool file name in workflow

charts/policy-hub/templates/job-policy-hub-migrations.yaml
remove selectorLabels from job
selectorLabels are unnecessary for job
=> chore: remove selectorLabels from job

docs/developer/Technical-Documentation/requests/example-requests.md, docs/developer/Technical-Documentation/requests/policy-hub.postman_collection.json
* add postman collection
* add documentation with example requests
To have some example requests and explanation for the requests as well as a postman collection to test the policy hub
N/A
=> chore(documentation): add request documentation

docs/technical-documentation/Security_Assessment.md
Creation of the draft document for Policy Hub Security Assessment
Necessary for the upcoming QG. 
https://github.com/eclipse-tractusx/sig-security/issues/56
https://github.com/eclipse-tractusx/sig-release/issues/504
=> docs: create security assessment

charts/policy-hub/templates/secret-external-db.yaml, charts/policy-hub/values.yaml
- fix label and username for external database
disabling the db dependency results in an error
na
=> fix(helm): fix label and username for external database

src/hub/PolicyHub.Service/Controllers/PolicyHubController.cs, tests/hub/PolicyHub.Service.Tests/Controllers/PolicyHubControllerTests.cs
Correct/Update the swagger docu of the policy hub.
Endpoint: /api/policy-hub/policy-types
Endpoint: /api/policy-hub/policy-content
Endpoint: /api/policy-hub/policy-content
Endpoint: /api/policy-hub/policy-types
Type: GET
update the summary of the endpoint to "Provides all current supported policy types incl. a policy description and useCase link"
Endpoint: /api/policy-hub/policy-content
Type: GET
update the summary of the endpoint to "Receive the policy template "access" or "usage" for a single policy rule based on the request parameters submitted by the user."
recheck if the parameter "UseCase" is really needed. Please analyse once for what the parameter is used; share the information with the Product Owner and agree on the next steps
Update the description of the endpoint parameter Type …
=> docs(policy): swagger document update

.github/workflows/chart-release.yaml, .github/workflows/chart-test.yml, .github/workflows/dependencies.yml, .github/workflows/kics.yml, .github/workflows/lint-pull-request.yml, .github/workflows/migrations-docker.yml, .github/workflows/release.yml, .github/workflows/release_candidate.yml, .github/workflows/service-docker.yml, .github/workflows/sonarcloud.yml, .github/workflows/test-automation.yml, .github/workflows/trivy-dev.yml, .github/workflows/trivy.yml, .github/workflows/unit.tests-formatting.yml
upgrade gh actions and change to pinned actions full length commit sha
https://github.com/eclipse-tractusx/portal/issues/225
=> chore(gh-actions): upgrade and change to pinned commit sha

.github/workflows/sonarcloud.yml, .github/workflows/test-automation.yml, .github/workflows/unit.tests-formatting.yml, DEPENDENCIES, README.md, docker/Dockerfile-policy-hub-migrations, docker/Dockerfile-policy-hub-service, docker/notice-policy-hub-migrations.md, docker/notice-policy-hub-service.md, src/database/PolicyHub.DbAccess/PolicyHub.DbAccess.csproj, src/database/PolicyHub.Entities/PolicyHub.Entities.csproj, src/database/PolicyHub.Migrations/PolicyHub.Migrations.csproj, src/hub/PolicyHub.Service/Controllers/PolicyHubController.cs, src/hub/PolicyHub.Service/Extensions/RouteHandlerBuilderExtensions.cs, src/hub/PolicyHub.Service/PolicyHub.Service.csproj, tests/database/PolicyHub.DbAccess.Tests/HubRepositoriesTests.cs, tests/database/PolicyHub.DbAccess.Tests/PolicyHub.DbAccess.Tests.csproj, tests/database/PolicyHub.DbAccess.Tests/PolicyRepositoryTests.cs, tests/database/PolicyHub.Entities.Tests/PolicyHub.Entities.Tests.csproj, tests/hub/PolicyHub.Service.Tests/Authentication/KeycloakClaimsTransformationTests.cs, tests/hub/PolicyHub.Service.Tests/BusinessLogic/PolicyHubBusinessLogicTests.cs, tests/hub/PolicyHub.Service.Tests/Controllers/PolicyHubControllerTests.cs, tests/hub/PolicyHub.Service.Tests/PolicyHub.Service.Tests.csproj
* upgrade nuget packages
* remove configureAwait from unit tests
Since .NET 7 is only supported until May 14, 2024 the portal services and jobs are upgraded to .NET 8 which is an LTS version
Refs: #19
=> feat(net8): upgrade to .net8

src/hub/PolicyHub.Service/BusinessLogic/PolicyHubBusinessLogic.cs, tests/hub/PolicyHub.Service.Tests/BusinessLogic/PolicyHubBusinessLogicTests.cs, tests/hub/PolicyHub.Service.Tests/Controllers/PolicyHubControllerTests.cs
Update the policy hub used policy template for the endpoint.
POST /api/policy-hub/policy-content endpoint:
Additionally to the generic structure - the support of "OR" constraintOperand for usage constraints are not supported for now.
Since this is in general allowed but not used by catena-x; i suggest instead of deleting the code to comment out the option to set an "OR" connection.
Note: access policies with an "OR" connection are still allowed (as shared above).
#43 
=> feat(template): policyhub template update

src/database/PolicyHub.Migrations/Migrations/20240430122950_1.0.0-rc.1.Designer.cs, src/database/PolicyHub.Migrations/Migrations/20240430122950_1.0.0-rc.1.cs, src/database/PolicyHub.Migrations/Migrations/PolicyHubContextModelSnapshot.cs
Merge all migrations since the last release into one migration
To have one consolidated migration
https://github.com/eclipse-tractusx/policy-hub/issues/59
=> build(migrations): merge all migrations since the last release

.github/workflows/chart-test.yml, .github/workflows/owasp-zap.yml, charts/policy-hub/README.md, charts/policy-hub/templates/deployment-hub.yaml, charts/policy-hub/templates/job-policy-hub-migrations.yaml, charts/policy-hub/values.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
rename policyhub node to service and policyhubmigrations to migrations
improve helm chart
=> feat(helm): consolidate structure in values.yaml

README.md
This PR fixes the broken link to the documentation in the README.
=> docs: fix README docs link

src/database/PolicyHub.DbAccess/PolicyHub.DbAccess.csproj, src/database/PolicyHub.Entities/PolicyHub.Entities.csproj, src/database/PolicyHub.Migrations/PolicyHub.Migrations.csproj, tests/database/PolicyHub.DbAccess.Tests/PolicyHub.DbAccess.Tests.csproj, tests/hub/PolicyHub.Service.Tests/PolicyHub.Service.Tests.csproj
increase efcore version to latest 8.0.7
efcore 8.0.3 has transitive dependency System.Text.Json 8.0.0 which has a security-vulerability that is clasified as high. Upgrade to efcore 8.0.7 implicitly upgrades this dependency to System.Text.Json 8.0.4 which resolves the vulnerability.
https://github.com/eclipse-tractusx/portal/issues/369
=> chore(dependencies): bump efcore to 8.0.7

charts/policy-hub/templates/configmap-postgres-init.yaml
schema used by the database migrations is "policy-hub" https://github.com/eclipse-tractusx/policy-hub/blob/v1.1.0-rc.1/src/database/PolicyHub.Entities/PolicyHubContext.cs#L55 and this inconsistency lead to the creation of one "hub" unused schema
don't create irrelevant schema
na
=> chore(helm): create same database schema as migrations

DEPENDENCIES, src/database/PolicyHub.DbAccess/PolicyHub.DbAccess.csproj, src/database/PolicyHub.Migrations/PolicyHub.Migrations.csproj, src/database/PolicyHub.Migrations/Program.cs, src/hub/PolicyHub.Service/BusinessLogic/PolicyHubBusinessLogic.cs, src/hub/PolicyHub.Service/PolicyHub.Service.csproj, src/hub/PolicyHub.Service/Program.cs, tests/database/PolicyHub.Entities.Tests/PolicyHub.Entities.Tests.csproj, tests/hub/PolicyHub.Service.Tests/PolicyHub.Service.Tests.csproj
framework version updated to 2.4.2
fix codeql-findings (nullable and use of async in program.cs)
frameworks was referencing outdated System.Text.Json 8.0.0 which has a vulnerability-issue that must be fixed. Upgrading to frameworks 2.4.2 implicitly resolves this outdated dependency.
https://github.com/eclipse-tractusx/portal/issues/369
=> chore(dependencies): enforce System.Text.Json version 8.0.4

src/hub/PolicyHub.Service/BusinessLogic/PolicyHubBusinessLogic.cs, src/hub/PolicyHub.Service/Controllers/PolicyHubController.cs, tests/hub/PolicyHub.Service.Tests/BusinessLogic/PolicyHubBusinessLogicTests.cs
Enhanced the filter GET/POST for policyContent end point
The current implementation of the GET/POST endpoint in the Policy Hub does not respond as expected when fetching a policy based on specific criteria
N/a
=> fix: policy hub  post get policy rules response structuring error value map

src/database/PolicyHub.Migrations/Seeder/Data/policies.json, src/database/PolicyHub.Migrations/Seeder/Data/policy_attributes.json, tests/database/PolicyHub.DbAccess.Tests/PolicyRepositoryTests.cs, tests/hub/PolicyHub.Service.Tests/Controllers/PolicyHubControllerTests.cs
update incorrect seeding data and not supported policies
The current seeding image has a number of incorrect/not supported policies.
Na
=> fix: update incorrect seeding data and not supported policies

README.md, docs/README.md, docs/api/API_Doc.md
Add API Hub links to the documentation
To have the api hub linked in the docs
N/A
=> docs: add api hub to docs

CONTRIBUTING.md
Fix the "How to Contribute" link.
The existing link is broken.
[Issue #483](https://github.com/eclipse-tractusx/portal/issues/483) 
=> docs: fix how to contribute link

.github/workflows/codeql.yml, .github/workflows/dependencies.yml, .github/workflows/sonarcloud.yml, .github/workflows/test-automation.yml, .github/workflows/unit.tests-formatting.yml, DEPENDENCIES, README.md, docker/Dockerfile-policy-hub-migrations, docker/Dockerfile-policy-hub-service, docker/notice-policy-hub-migrations.md, docker/notice-policy-hub-service.md, src/database/PolicyHub.DbAccess/PolicyHub.DbAccess.csproj, src/database/PolicyHub.Entities/PolicyHub.Entities.csproj, src/database/PolicyHub.Migrations/PolicyHub.Migrations.csproj, src/database/PolicyHub.Migrations/Program.cs, src/hub/PolicyHub.Service/PolicyHub.Service.csproj, tests/database/PolicyHub.DbAccess.Tests/PolicyHub.DbAccess.Tests.csproj, tests/database/PolicyHub.Entities.Tests/PolicyHub.Entities.Tests.csproj, tests/hub/PolicyHub.Service.Tests/PolicyHub.Service.Tests.csproj
Upgrade .NET to v9
To have the latest dotnet version in the projects
n/a
=> chore(net9): update version to net9

src/database/PolicyHub.DbAccess/IHubRepositories.cs
remove public access-modifier on interface-method
interface methods must not declare access-modifiers. The issue blocks https://github.com/eclipse-tractusx/policy-hub/pull/224 as it causes the format-scan to fail
N/A
=> fix: access modifiers on interface

src/database/PolicyHub.DbAccess/IHubRepositories.cs, src/database/PolicyHub.DbAccess/PolicyHub.DbAccess.csproj, src/database/PolicyHub.Migrations/PolicyHub.Migrations.csproj, src/hub/PolicyHub.Service/BusinessLogic/PolicyHubBusinessLogic.cs, src/hub/PolicyHub.Service/ErrorHandling/ErrorMessageContainer.cs, src/hub/PolicyHub.Service/ErrorHandling/GeneralHttpErrorHandler.cs, src/hub/PolicyHub.Service/PolicyHub.Service.csproj, src/hub/PolicyHub.Service/Program.cs, tests/hub/PolicyHub.Service.Tests/BusinessLogic/PolicyHubBusinessLogicTests.cs, tests/hub/PolicyHub.Service.Tests/Controllers/PolicyHubControllerTests.cs
fixing the current error handling
after the net 9 upgrade the general error handling was broken and always returned a 500
N/A
=> fix(errorHandling): adjust general error handler

docs/api/hub-service.yaml, docs/api/postman/policy-hub.postman_collection.json, src/hub/PolicyHub.Service/BusinessLogic/PolicyHubBusinessLogic.cs, src/hub/PolicyHub.Service/Models/PolicyFileContent.cs, tests/hub/PolicyHub.Service.Tests/Controllers/PolicyHubControllerTests.cs
Description
In the returned policies, the policy hub adds the https://w3id.org/catenax/v0.0.1/ns/ context with the cx prefix, but then uses the cx-policy prefix instead.
Why
The cx-policy prefix isn’t bound to any context within the JSON-LD document and therefore will fail to expand during serialization.
Issue
N/A
Link to Github issue.
=> fix: Use correct JSON-LD context prefix

docs/api/hub-service.yaml, docs/api/postman/example-requests.md, src/hub/PolicyHub.Service/BusinessLogic/PolicyHubBusinessLogic.cs, src/hub/PolicyHub.Service/Models/PolicyFileContent.cs, tests/hub/PolicyHub.Service.Tests/Controllers/PolicyHubControllerTests.cs
- change the iri of the json-ld context namespace-declaration of cx-profile to 'https://w3id.org/catenax/policy/'
- add the mandatory property 'profile', value 'cx-policy:profile2405'
- add the namespace cx-policy to the values of 'leftOperant'
json-ld output is not complient with https://catenax-ev.github.io/docs/standards/CX-0018-DataspaceConnectivity
https://github.com/eclipse-tractusx/policy-hub/issues/262
=> fix(json-ld): adjust namespace and usage of cx-profile

.github/workflows/dependencies.yml
- fix dotnet list command: does work with dotnet 9.0.104 but not with 9.0.202 (currently latest), we switch this pipeline to 9.0.104 as a workaround https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/359
- restrict workflow to relevant paths
- check always for the restricted dependencies regardless if file was changed
#283
=> chore: fix and improve dependencies check
