eclipse-tractusx/policy-hub

- .tractusx
merge main to dev
to have the latest main on dev
N/A
> chore: merge main to dev

- charts/policy-hub/templates/configmap-postgres-init.yaml
- charts/policy-hub/templates/deployment-hub.yaml
- charts/policy-hub/templates/ingress.yaml
- charts/policy-hub/templates/job-policy-hub-migrations.yaml
- charts/policy-hub/templates/secret-external-db.yaml
- charts/policy-hub/templates/secret-postgres.yaml
- charts/policy-hub/templates/service-hub.yaml
- charts/policy-hub/values.yaml
- ensure unique resource names
- docs:  mention init script for external database
improve helm chart
> feat(helm-chart): ensure unique resource names

- .github/workflows/release_candidate.yml
- charts/policy-hub/README.md
- charts/policy-hub/README.md.gotmpl
update readme
change release candidate workflow trigger to match rc.x pattern
prepare release
> chore(v0.1.0-rc.1): update readme

- .github/pull_request_template.md
- .github/workflows/policy-hub-chart-test.yml
- .github/workflows/release-please.yml
- NOTICE.md
- charts/policy-hub/Chart.yaml
- charts/policy-hub/README.md
- charts/policy-hub/README.md.gotmpl
- charts/policy-hub/templates/deployment-hub.yaml
- charts/policy-hub/templates/job-policy-hub-migrations.yaml
- charts/policy-hub/values.yaml
- consortia/argocd-app-templates/appsetup-int.yaml
- consortia/argocd-app-templates/appsetup-pen.yaml
- consortia/argocd-app-templates/appsetup-stable.yaml
- consortia/environments/values-dev.yaml
- consortia/environments/values-rc.yaml
- docker/Dockerfile-policy-hub-migrations
- docker/Dockerfile-policy-hub-service
- docs/technical-documentation/architecture/Development Concept.md
- scripts/add_notice_footer.sh
- scripts/license.sh
- src/.vscode/settings.json
Merge all related release changes to main
To have the latest changes available in main
N/A
> chore(v0.1.0-rc.2): merge release into main

- .github/workflows/owasp-zap.yml
introduce OWASP ZAP scan for DAST
First successful run:
https://github.com/eclipse-tractusx/policy-hub/actions/runs/7876594609/job/21490948498
https://github.com/eclipse-tractusx/policy-hub/issues/29
> chore: introduce owasp zap scan

- charts/policy-hub/templates/configmap-postgres-init.yaml
- charts/policy-hub/templates/deployment-hub.yaml
- charts/policy-hub/templates/ingress.yaml
- charts/policy-hub/templates/job-policy-hub-migrations.yaml
- charts/policy-hub/templates/secret-external-db.yaml
- charts/policy-hub/templates/secret-postgres.yaml
- charts/policy-hub/templates/service-hub.yaml
- charts/policy-hub/values.yaml
- consortia/environments/values-beta.yaml
- consortia/environments/values-dev.yaml
- consortia/environments/values-int.yaml
- consortia/environments/values-pen.yaml
- consortia/environments/values-rc.yaml
improve ingress, labels and namespace setting
improve helm-chart
> feat(helm-chart): improve ingress, labels and namespace setting

- .github/workflows/release-please.yml
- docs/technical-documentation/release-process/Release Process.md
- change release-please trigger
- update release process docs
improve release
> chore: change release-please trigger and update docs

- docs/technical-documentation/architecture/Architecture Constraints.md
- docs/technical-documentation/architecture/Context and scope.md
- docs/technical-documentation/architecture/Requirements.md
Adding additional content to architecture documentation as well as image 
Getting ready for release 24.03.
https://github.com/eclipse-tractusx/portal-assets/issues/255
> docs: enhancing release 24.03. system documentation

- .github/dependabot.yml
improve dependabot settings
follow up to https://github.com/eclipse-tractusx/policy-hub/pull/73
https://github.com/eclipse-tractusx/portal/issues/219
> chore: improve dependabot settings

- .github/workflows/release.yml
fix release workflow due to invalid variable
invalid workflow
https://github.com/eclipse-tractusx/policy-hub/issues/59
> chore: fix release workflow due to invalid variable

- .github/dependabot.yml
add groups for version updates
https://github.com/eclipse-tractusx/portal/issues/300
> chore(dependabot): add groups for version updates

- docs/technical-documentation/architecture/Security_Assessment.md
Update of security assessment: no security-relevant changes to security assessment
Updated security assessment for 1.0.0
eclipse-tractusx/sig-release#672
> chore: update security assessment for 1.0.0

- .github/dependabot.yml
- src/database/PolicyHub.Entities/PolicyHub.Entities.csproj
npgsql: change to existing package
dependabot: improve grouping
eclipse-tractusx/portal-backend#731
https://github.com/eclipse-tractusx/portal/issues/300
> chore: change to existing package and improve dependabot

- .github/workflows/quality-gate-checks.yml
- README.md
- charts/policy-hub/README.md
During Review of the QGate #127, a few things were that small that I directly incorporated them.
Compliance to TRG is needed. Beside the issues listed, I added the QGate check workflow so that you automate a few checks a little :)
Following issues are resolved:
- #140 -> link to docs
- #141 -> added one line for installation
- #144  -> added prerequisites
> chore: incorporate small findings from qgate review

- DEPENDENCIES
- consortia/argocd-app-templates/appsetup-dev.yaml
- consortia/argocd-app-templates/appsetup-int.yaml
argocd templates: update namespace for dev and int
https://github.com/eclipse-tractusx/portal/issues/337
> chore(consortia): update namespace for dev and int

- .github/workflows/chart-test.yml
update version to upgrade from
maintenance
N/A
> chore(helm-test): update version to upgrade from

- .github/workflows/migrations-docker.yml
- .github/workflows/release.yml
- .github/workflows/release_candidate.yml
- .github/workflows/service-docker.yml
- docker/Dockerfile-policy-hub-migrations
- docker/Dockerfile-policy-hub-service
- change from emulation to cross-compile for building multi-platform images
- also, improve dockerfiles by removing unnecessary base stage and aligning environment variables
https://github.com/eclipse-tractusx/portal-backend/issues/802
https://docs.docker.com/build/building/multi-platform
https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support
> fix(image-build): change from emulation to cross-compile

- environments/helm-values/values-int.yaml
change to consolidation from https://github.com/eclipse-tractusx/policy-hub/pull/156
update deployment config
https://github.com/eclipse-tractusx/policy-hub/issues/171
> chore(1.1.0-rc.1): change structure in values.yaml of association env

- README.md
- docs/technical-documentation/known-knowns/known-issues-and-limitations.md
* add known knowns section to readme
* add known knows for the latest version
To give an overview of the known knowns
N/A
> docs: add known knowns section to readme

- .tractusx
- CHANGELOG.md
- charts/policy-hub/Chart.yaml
- charts/policy-hub/README.md
- docs/api/hub-service.yaml
- environments/argocd-app-templates/appsetup-int.yaml
- environments/argocd-app-templates/appsetup-stable.yaml
- src/Directory.Build.props
finalize version 1.2.0-rc.1 by merge into main
https://github.com/eclipse-tractusx/portal/issues/465
> build(1.2.0-rc.1): bump version and update docs

- .github/workflows/trivy-main.yml
- .github/workflows/trivy.yml
- .tractusx
- charts/policy-hub/Chart.yaml
- charts/policy-hub/README.md
- docs/api/hub-service.yaml
- environments/argocd-app-templates/appsetup-int.yaml
- environments/argocd-app-templates/appsetup-stable.yaml
- src/Directory.Build.props
prepare release finalisation of of version 1.2.0
https://github.com/eclipse-tractusx/portal/issues/482
> build(1.2.0): bump version and update docs

- .github/workflows/trivy-main.yml
- .github/workflows/trivy.yml
- .tractusx
- charts/policy-hub/Chart.yaml
- charts/policy-hub/README.md
- docs/api/hub-service.yaml
- environments/argocd-app-templates/appsetup-int.yaml
- environments/argocd-app-templates/appsetup-stable.yaml
- src/Directory.Build.props
merge latest changes into main
https://github.com/eclipse-tractusx/portal/issues/482
> build(1.2.0): merge latest changes into main

- .tractusx
- CHANGELOG.md
- charts/policy-hub/Chart.yaml
- charts/policy-hub/README.md
- docs/api/hub-service.yaml
- environments/argocd-app-templates/appsetup-int.yaml
- environments/argocd-app-templates/appsetup-stable.yaml
- src/Directory.Build.props
Merge the latest release into main
To have the latest changes available in the main branch
https://github.com/eclipse-tractusx/portal/issues/502
> build(1.3.0-rc.1): merge release into main

- .github/workflows/chart-test.yml
- .github/workflows/codeql.yml
- .github/workflows/dependencies.yml
- .github/workflows/kics.yml
- .github/workflows/owasp-zap.yml
- .github/workflows/release.yml
- .github/workflows/test-automation.yml
- .github/workflows/trivy-main.yml
- .github/workflows/trivy.yml
- .github/workflows/trufflehog.yml
- .tractusx
- charts/policy-hub/Chart.yaml
- charts/policy-hub/README.md
- docs/api/hub-service.yaml
- environments/argocd-app-templates/appsetup-int.yaml
- environments/argocd-app-templates/appsetup-stable.yaml
- src/Directory.Build.props
prepare release finalisation of of version 1.3.0
https://github.com/eclipse-tractusx/sig-release/issues/1134
> build(1.3.0): bump version and update docs

- DEPENDENCIES
- docs/api/hub-service.yaml
- src/database/PolicyHub.DbAccess/PolicyHub.DbAccess.csproj
- src/database/PolicyHub.Entities/PolicyHub.Entities.csproj
- src/database/PolicyHub.Migrations/PolicyHub.Migrations.csproj
- src/hub/PolicyHub.Service/PolicyHub.Service.csproj
- tests/database/PolicyHub.DbAccess.Tests/PolicyHub.DbAccess.Tests.csproj
- tests/database/PolicyHub.Entities.Tests/PolicyHub.Entities.Tests.csproj
- tests/hub/PolicyHub.Service.Tests/PolicyHub.Service.Tests.csproj
update the dependencies
to have the latest version of the external packages available
Refs: #281
> chore: update dependencies

- .tractusx
- CHANGELOG.md
- charts/policy-hub/Chart.yaml
- charts/policy-hub/README.md
- docs/api/hub-service.yaml
- environments/argocd-app-templates/appsetup-int.yaml
- environments/argocd-app-templates/appsetup-stable.yaml
- src/Directory.Build.props
* bump version
* update docs
To prepare the branch for the release v1.3.1-rc.1
[#541](https://github.com/eclipse-tractusx/portal/issues/541)
> build(1.3.1-rc.1): bump version and update docs
